#ifndef GUARD_GBA_IO_H
#define GUARD_GBA_IO_H

#include "gba_types.h"

/* Hardware register definitions.
 *
 * The volatile qualifiers affect the memory accesses and instruction ordering
 * generated by agbcc (docs/COMPILER.md, rules 4 and 12). These declarations were
 * selected by comparing compiled output with the ROM; changing a qualifier can
 * break byte-matching. When adding a register, compare both access forms with
 * the ROM and verify the result with `make matching`. */

typedef struct {
    const void *src;
    void *dst;
    u32 control;
} DmaChannel;

/* Raw register addresses for code that needs a constant address expression
 * instead of a dereferenced register macro (docs/COMPILER.md, rule 22:
 * reassigning a pointer from a constant address). */
#define REG_DISPCNT_ADDR  0x04000000
#define REG_DISPSTAT_ADDR 0x04000004
#define REG_VCOUNT_ADDR   0x04000006
#define REG_BG1VOFS_ADDR  0x04000016
#define REG_KEYINPUT_ADDR 0x04000130
#define REG_BLDCNT_ADDR   0x04000050
#define REG_BLDALPHA_ADDR 0x04000052
#define REG_BLDY_ADDR     0x04000054
#define REG_DMA3_ADDR     0x040000D4
#define REG_TM3CNT_ADDR   0x0400010C
#define REG_SIOCNT_ADDR   0x04000128
#define REG_RCNT_ADDR     0x04000134
#define REG_SIOMLT_SEND_ADDR 0x0400012A
#define REG_TM3CNT_H_ADDR 0x0400010E
#define REG_IE_ADDR       0x04000200
#define REG_IF_ADDR       0x04000202
#define REG_WAITCNT_ADDR  0x04000204
#define REG_IME_ADDR      0x04000208

#define REG_DISPCNT  (*(u16 *)REG_DISPCNT_ADDR)
#define REG_DISPSTAT (*(volatile u16 *)REG_DISPSTAT_ADDR)
#define REG_VCOUNT   (*(volatile u16 *)REG_VCOUNT_ADDR)
#define REG_BG1VOFS  (*(volatile u16 *)REG_BG1VOFS_ADDR)
#define REG_KEYINPUT (*(volatile u16 *)REG_KEYINPUT_ADDR)
#define REG_BLDCNT   (*(u16 *)REG_BLDCNT_ADDR)
#define REG_BLDALPHA (*(u16 *)REG_BLDALPHA_ADDR)
#define REG_BLDY     (*(u16 *)REG_BLDY_ADDR)
#define REG_DMA3     (*(volatile DmaChannel *)REG_DMA3_ADDR)
/* A 32-bit write covers both the timer reload and control halfwords. */
#define REG_TM3CNT   (*(u32 *)REG_TM3CNT_ADDR)
#define REG_SIOCNT   (*(volatile u16 *)REG_SIOCNT_ADDR)
#define REG_RCNT     (*(volatile u16 *)REG_RCNT_ADDR)
#define REG_SIOMLT_SEND (*(volatile u16 *)REG_SIOMLT_SEND_ADDR)
/* SIO control and send registers occupy consecutive halfwords. The ROM
 * accesses both through one base register (`strh r0,[r2,#2]`); separate absolute
 * addresses introduce an extra literal. This struct view preserves that layout.
 */
typedef struct SioRegs {
    u16 control;                    /* +0x00 */
    u16 send;                       /* +0x02 */
} SioRegs;
#define REG_SIO (*(volatile SioRegs *)REG_SIOCNT_ADDR)
#define REG_TM3CNT_H (*(volatile u16 *)REG_TM3CNT_H_ADDR)
/* Some SIOCNT accesses use a 32-bit load: one `ldr` reads the error bit
 * together with the adjacent upper halfword (observed at 0x0806686C). */
#define REG_SIOCNT32 (*(volatile u32 *)REG_SIOCNT_ADDR)
#define REG_IE       (*(volatile u16 *)REG_IE_ADDR)
#define REG_IF       (*(volatile u16 *)REG_IF_ADDR)
#define REG_WAITCNT  (*(volatile u16 *)REG_WAITCNT_ADDR)
#define REG_IME      (*(volatile u16 *)REG_IME_ADDR)

/* BIOS interrupt-check flags. The default declaration is non-volatile:
 * adding volatile changes constant/load ordering in existing matching code.
 * Some call sites require a volatile access through an explicit cast; the
 * required access form depends on the ROM instructions at that site. */
extern u16 gBiosIrqFlags;   /* 0x03007FF8 */

/* DMA register view with a 16-bit control field.
 *
 * DmaChannel above combines the transfer count and control bits in one u32,
 * as used for DMA3 fills. Channel-disable routines mask only the upper
 * halfword, so they need this separate view. The ROM keeps the source-address
 * register (SAD) as the base and writes at offset +0x0A; this struct provides
 * the corresponding layout. */
typedef struct DmaRegs {
    const void *src;                /* +0x00 */
    void       *dst;                /* +0x04 */
    u16         count;              /* +0x08 */
    u16         control;            /* +0x0A */
} DmaRegs;

#define REG_DMA0 (*(volatile DmaRegs *)0x040000B0)
#define REG_DMA1 (*(volatile DmaRegs *)0x040000BC)
#define REG_DMA2 (*(volatile DmaRegs *)0x040000C8)
#define REG_DMA3H (*(volatile DmaRegs *)0x040000D4)

#define REG_BG0CNT   (*(u16 *)0x04000008)
#define REG_BG1CNT   (*(u16 *)0x0400000A)
#define REG_BG2CNT   (*(u16 *)0x0400000C)
#define REG_BG3CNT   (*(u16 *)0x0400000E)

#define EWRAM_BASE 0x02000000
#define IWRAM_BASE 0x03000000
#define VRAM_BASE  0x06000000
#define OAM_BASE   0x07000000

#endif /* GUARD_GBA_IO_H */
